### ISSUE TITLE
Update Footer Links, Terms, and Privacy Policy

### ISSUE THREAD

**Issue by dwmoore** [merlotsart/merlotsart#2]
~~1. Remove the "Partner with us" link and move it to the footer
2. Add footer links: Terms, Privacy, Partner with us, Contact (in white text because the purple text is not visible.~~ Fixed in https://github.com/merlotsart/merlotsart/commit/d43a1f93cf309489adc28f3238244324109285b2

Below are the terms and privacy for the footer links.

Terms: https://www.dropbox.com/s/b0p2uzh5k5nxwt9/MerlotsArt_Terms%20of%20Service%203.16.docx?dl=0
Privacy: https://www.dropbox.com/s/oxbzqzll9z6mlpx/Privacy%20Statement.docx?dl=0

**Comment by dwmoore** [comment]
Holding on the terms and privacy copy pending email reply. Current format is docx and hoping to get a structured plain text to make implementation quicker.

**Comment by merlotsart** [comment]
Hi Dave,

Please let me know if the text files work for the Privacy and Terms.

On Sun, Mar 20, 2016 at 6:25 PM, Dave Moore notifications@github.com
wrote:

> Holding on the terms and privacy copy pending email reply. Current format
> is docx and hoping to get a structured plain text to make implementation
> quicker.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/merlotsart/merlotsart/issues/2#issuecomment-199047699

PRIVACY STATEMENT
What this Privacy Policy Covers:ĘThe practices described in this Policy only apply to the following:
- Information collected online on this Site.
  What this Privacy Policy Does Not Cover:ĘThis Policy does not cover any of the following:
- Information you give to us offline, for example when you send a letter to our business address or leave a message on our voicemail system.
  SECTION 1 - WHAT DO WE DO WITH YOUR INFORMATION?
  When you purchase something from our site, as part of the buying and selling process, we collect the personal information you give us such as your name, address and email address.  
- Personally Identifiable Information.
  MerlotŐs Art will use your Personally Identifiable Information for the purposes for which it was provided. We may use your Personally Identifiable Information to notify you of changes to an event for which you registered, notifications about special opportunities and other events you may be interested in, and to request your participation in surveys or other promotions. Our email newsletters and other general email marketing communications also include an 'unsubscribe' opt-out link that you may use to ask that we discontinue such emails to you.
- Aggregate InformationĘĐ MerlotŐs Art also combines your usage information for the Site or other Service with that of other users (ŇAggregate InformationÓ) to determine which features and areas of the Site or other Service are most popular. Aggregate Information does not contain any of your Personally Identifiable Information. By collecting and analyzing this data, MerlotŐs Art can improve the Site or other Service.
- Interest Based AdvertisingĘĐ MerlotŐs Art will display ads based on information that we, or agencies that MerlotŐs Art utilizes, have collected or received about your activities and interests based on your online activities. MerlotŐs Art also does not target ads to users based on sensitive health data. If you donŐt want to receive interest based advertising you canĘopt out.
  When you browse our site, we also automatically receive your computerŐs internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system.
  Email marketing (if applicable): With your permission, we may send you emails about our services, new products and other updates.

SECTION 2 - CONSENT
How do you get my consent?
When you provide us with personal information to complete a transaction, verify your credit card, place an order, arrange for a delivery or return a purchase, we imply that you consent to our collecting it and using it for that specific reason only.
If we ask for your personal information for a secondary reason, like marketing, we will either ask you directly for your expressed consent, or provide you with an opportunity to say no.
How do I withdraw my consent?
If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the continued collection, use or disclosure of your information, at anytime, by contacting us at info@merlotsart.com or mailing us at: Merlots Art LLC 1512 U Street Washington DC United States 20009

SECTION 3 - DISCLOSURE
We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.

SECTION 4 Đ DATA STORAGE
Your data is stored through our data storage, databases on a secure server behind a firewall.
Payment:
If you choose a direct payment gateway to complete your purchase, we store your credit card data. It is encrypted through the Payment Card Industry Data Security Standard (PCI-DSS). Your purchase transaction data is stored only as long as is necessary to complete your purchase transaction. After that is complete, your purchase transaction information is deleted.
All direct payment gateways adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover.
PCI-DSS requirements help ensure the secure handling of credit card information by our store and its service providers.

SECTION 5 - THIRD-PARTY SERVICES
In general, the third-party providers used by us will only collect, use and disclose your information to the extent necessary to allow them to perform the services they provide to us.
However, certain third-party service providers, such as payment gateways and other payment transaction processors, have their own privacy policies in respect to the information we are required to provide to them for your purchase-related transactions.
For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers.
In particular, remember that certain providers may be located in or have facilities that are located a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.
As an example, if you are located in Canada and your transaction is processed by a payment gateway located in the United States, then your personal information used in completing that transaction may be subject to disclosure under United States legislation, including the Patriot Act.
Once you leave our storeŐs website or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy or our websiteŐs Terms of Service. 
Links
When you click on links on our site, they may direct you away from our site. We are not responsible for the privacy practices of other sites and encourage you to read their privacy statements.

SECTION 6 - SECURITY
To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.
If you provide us with your credit card information, the information is encrypted using secure socket layer technology (SSL) and stored with a AES-256 encryption.  Although no method of transmission over the Internet or electronic storage is 100% secure, we follow all PCI-DSS requirements and implement additional generally accepted industry standards.

SECTION 7 - COOKIES
Here is a list of cookies that we use. WeŐve listed them here so you that you can choose if you want to opt-out of cookies or not.

SECTION 8 - AGE OF CONSENT
By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.

SECTION 9 - CHANGES TO THIS PRIVACY POLICY
We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website. If we make material changes to this policy, we will notify you here that it has been updated, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it.
If our store is acquired or merged with another company, your information may be transferred to the new owners so that we may continue to sell products to you.

QUESTIONS AND CONTACT INFORMATION
If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information contact our Privacy Compliance Officer at info@merlotsart.com or by mail at Merlots Art LLC
[Re: Privacy Compliance Officer]
[1512 U Street Washington DC United States 20009]

---

TERMS OF SERVICE

OVERVIEW
This website is operated by Merlots Art LLC. Throughout the site, the terms �we�, �us� and �our� refer to Merlots Art LLC. Merlots Art LLC offers this website, including all information, tools and services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.
By visiting our site and/ or purchasing something from us, you engage in our �Service� and agree to be bound by the following terms and conditions (�Terms of Service�, �Terms�), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms of Service apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of content.
Please read these Terms of Service carefully before accessing or using our website. By accessing or using any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any services. If these Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service.
Any new features or tools which are added to the current store shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes.

SECTION 1 - ONLINE STORE TERMS
By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.
You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).

You must not transmit any worms or viruses or any code of a destructive nature.
A breach or violation of any of the Terms will result in an immediate termination of your Services.

SECTION 2 - GENERAL CONDITIONS
We reserve the right to refuse service to anyone for any reason at any time.
You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.
You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us.
The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.

SECTION 3 - ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION
We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site is at your own risk.
This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site.

SECTION 4 - MODIFICATIONS TO THE SERVICE AND PRICES
Prices for our products are subject to change without notice.
We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.
We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.

SECTION 5 - PRODUCTS OR SERVICES
ART CLASSES & EVENTS:
Registering for events sold on our site indicate that you agree to the terms below:� Participants must be 21 and over to drink alcohol; Please drink responsibly.
LATE ARRIVALS: daily deal vouchers such are subject to forfeiture (if applicable).  We cannot guarantee the optimal experience if you arrive 30 minutes after the start time of an event. Reservations and seating are first-come, first-served. If you bring your own bottle (1512 U Street studio only), open or empty wine bottles may not be removed from the studio.
NO REFUNDS: A credit can be issued for another event. 48 hour cancellation or reschedule notice required. 
CANCELLATIONS: Classes are subject to cancellation if less than 10 painters are registered.

Certain products or services may be available exclusively online through the website. These products or services may have limited quantities and are subject to return or exchange only according to our Return Policy.
We have made every effort to display as accurately as possible the colors and images of our products that appear at the store. We cannot guarantee that your computer monitor's display of any color will be accurate.
We reserve the right, but are not obligated, to limit the sales of our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at anytime without notice, at the sole discretion of us. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited.
We do not warrant that the quality of any products, services, information, or other material purchased or obtained by you will meet your expectations, or that any errors in the Service will be corrected.

SECTION 6 - ACCURACY OF BILLING AND ACCOUNT INFORMATION
We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors.
You agree to provide current, complete and accurate purchase and account information for all purchases made at our store. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed.
For more detail, please review our Returns Policy.

SECTION 7 - OPTIONAL TOOLS
We may provide you with access to third-party tools over which we neither monitor nor have any control nor input.
You acknowledge and agree that we provide access to such tools �as is� and �as available� without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools.

Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s).
We may also, in the future, offer new services and/or features through the website (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms of Service.

SECTION 8 - THIRD-PARTY LINKS
Certain content, products and services available via our Service may include materials from third-parties.
Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.
We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.

SECTION 9 - USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS
If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.
We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party�s intellectual property or these Terms of Service.
You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party.

SECTION 10 - PERSONAL INFORMATION
Your submission of personal information through the store is governed by our Privacy Policy. To view our Privacy Policy.

SECTION 11 - ERRORS, INACCURACIES AND OMISSIONS
Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order).
We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.

SECTION 12 - PROHIBITED USES
In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.

SECTION 13 - DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY
We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free.
We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable.
You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.
You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.
IN NO CASE SHALL MERLOTS ART LLC, OUR DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, INTERNS, ORGANIZERS, SUPPLIERS, SERVICE PROVIDERS, LICENSEES OR LICENSORS BE LIABLE FOR ANY INJURY, LOSS, CLAIM, OR ANY DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING, WITHOUT LIMITATION LOST PROFITS, LOST REVENUE, LOST SAVINGS, LOSS OF DATA, REPLACEMENT COSTS, OR ANY SIMILAR DAMAGES, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, ARISING FROM YOUR USE OF ANY OF THE SERVICE OR ANY PRODUCTS PROCURED USING THE SERVICE, OR FOR ANY OTHER CLAIM RELATED IN ANY WAY TO YOUR USE OF THE SERVICE OR ANY PRODUCT, INCLUDING, BUT NOT LIMITED TO, ANY ERRORS OR OMISSIONS IN ANY CONTENT, OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SERVICE OR ANY CONTENT (OR PRODUCT) POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICE, EVEN IF ADVISED OF THEIR POSSIBILITY. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, OUR LIABILITY SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.

SECTION 14 � WAIVER AND RELEASE OF LIABILITY
IN CONSIDERATION OF BEING ALLOWED TO PARTICIPATE IN MERLOTS ART EVENTS AND ACTIVITIES, I HEREBY RELEASE, WAIVE, DISCHARGE AND COVENANT NOT TO SUE MERLOTS ART LLC AND ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, INTERNS, ORGANIZERS, SUPPLIERS, SERVICE PROVIDERS, LICENSEES OR LICENSORS FROM ANY AND ALL LIABILITY, CLAIMS, DEMANDS, OR CAUSES OF ACTION WHATSOEVER ARISING OUT OF OR RELATED TO ANY LOSS, DAMAGE, OR INJURY, INCLUDING DEATH, THAT MAY BE SUSTAINED BY ME, OR TO ANY PROPERTY BELONGING TO ME WHILE PARTICIPATING IN MERLOTS ART EVENTS AND ACTIVITIES, OR FOR TREATMENT OR ACTION UNDERTAKEN AS A RESULT OF INJURY OR EMOTIONAL DISTRESS WHILE ON THE PREMISES WHERE THE FESTIVAL PROGRAMS ARE BEING CONDUCTED, NO MATTER THE CAUSE.
I VOLUNTARILY ASSUME FULL RESPONSIBILITY FOR ANY RISK OF LOSS, PROPERTY DAMAGE OR PERSONAL INJURY, INCLUDING DEATH, THAT MAY BE SUSTAINED BY ME, OR ANY LOSS OR DAMAGE TO PROPERTY OWNED BY ME AS A RESULT OF BEING A PARTICIPANT IN MERLOTS ART EVENTS AND ACTIVITIES, NO MATTER THE CAUSE. I GIVE PERMISSION TO THE LEADER AND ORGANIZERS TO SEEK MEDICAL OR OTHER SERVICES FOR ANY INJURY OR EMOTIONAL DISTRESS.

SECTION 15 - INDEMNIFICATION
You agree to indemnify, defend and hold harmless Merlots Art LLC and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys� fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.

SECTION 16 � RIGHTS TO USE IMAGE
As a participant in Merlots Art events and activities I hereby give the irrevocable and unrestricted rights to use my image, name, voice, and likeness for use by Merlots Art LLC in such materials as brochures, videos, and on websites for the purposes of promoting the Merlots Art events and activities.

SECTION 17 - SEVERABILITY
In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.

SECTION 18 - TERMINATION
The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.
These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site.
If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).

SECTION 19 - ENTIRE AGREEMENT
The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.
These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service).
Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.

SECTION 20 - GOVERNING LAW
These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of 1512 U Street Washington DC United States 20009.

SECTION 22 - CHANGES TO TERMS OF SERVICE
You can review the most current version of the Terms of Service at any time at this page.
We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.

SECTION 23 - CONTACT INFORMATION
Questions about the Terms of Service should be sent to us at info@merlotsart.com.

**Comment by dwmoore** [comment]
The attached copy still contains the docx format errors. For example in the second line, "What this Privacy Policy Covers:ĘThe practices". Also within the terms document, "the terms �we�, �us� and..."

I can go through and try to make the needed changes, the only thing is that it takes time (which I know we are trying to conserve).

I'll also need a sign off that I am not providing legal documents or advice, rather editing your documents at your request and without any consideration given to legal status or ramifications of verbiage.

Thanks!

**Comment by merlotsart** [comment]
Hi Dave,

I'm going to see if there's another way to turn the Word into a text file
without the errors.  If not, please use the text file you have.

I am providing sign off that you are only editing the final legal documents
and NOT providing legal documents or advice.

Raiquel

**Comment by merlotsart** [comment]
Hi Dave,

I tried to fix the Privacy and Terms text files and those errors didn't
appear in my file.  Please proceed with the corrections.

I am providing sign off that you are only editing the final legal documents
and NOT providing legal documents or advice.

Thanks!
Raiquel

**Comment by dwmoore** [comment]
Fixed in https://github.com/merlotsart/merlotsart/commit/910fc974fe13852bd3b1928854250cc2f6e57ca2

**Comment by merlotsart** [comment]
Thanks!
